import type { AppState } from '../shared/types.js';

const now = new Date('2026-08-06T12:00:00.000Z');
const isoDaysAgo = (days: number, hours = 0) => new Date(now.getTime() - (days * 24 + hours) * 60 * 60 * 1000).toISOString();
const isoDaysAhead = (days: number) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000).toISOString();

export const seedState: AppState = {
  schemaVersion: 1,
  workspace: {
    name: 'Northstar Creative',
    shortName: 'Northstar',
    logoText: 'N',
    accent: '#2f5d50',
    surface: 'paper',
    portalHeadline: 'Review the work. Leave clear feedback. Approve with confidence.',
    approvalDisclaimer: 'Approval confirms that this revision is accepted as final for the milestone shown above.',
    emailFromName: 'Maya at Northstar',
    requireClientName: true,
    allowDownloads: true,
    showRevisionHistory: true,
  },
  integrations: {
    database: false,
    email: false,
    cloudinary: false,
    slack: false,
  },
  clients: [
    {
      id: 'client-ember',
      name: 'Dara Okafor',
      company: 'Ember Coffee',
      email: 'dara@ember.example',
      avatar: 'DO',
      activeProjects: 1,
      lastActiveAt: isoDaysAgo(0, 2),
      status: 'active',
    },
    {
      id: 'client-loom',
      name: 'Mina Cole',
      company: 'Loom House',
      email: 'mina@loom.example',
      avatar: 'MC',
      activeProjects: 1,
      lastActiveAt: isoDaysAgo(1),
      status: 'active',
    },
    {
      id: 'client-field',
      name: 'Theo Mensah',
      company: 'Field Notes Studio',
      email: 'theo@fieldnotes.example',
      avatar: 'TM',
      activeProjects: 1,
      lastActiveAt: isoDaysAgo(3),
      status: 'invited',
    },
    {
      id: 'client-sonder',
      name: 'Avery Chen',
      company: 'Sonder Health',
      email: 'avery@sonder.example',
      avatar: 'AC',
      activeProjects: 0,
      lastActiveAt: isoDaysAgo(12),
      status: 'archived',
    },
  ],
  projects: [
    {
      id: 'project-ember-packaging',
      name: 'Summer Packaging Redesign',
      clientId: 'client-ember',
      clientName: 'Ember Coffee',
      category: 'Brand & Packaging',
      status: 'in-review',
      dueAt: isoDaysAhead(4),
      updatedAt: isoDaysAgo(0, 1),
      progress: 78,
      description: 'A bright seasonal packaging system for Ember Coffee’s cold brew and retail bean range.',
      cover: '/assets/ember-v3.svg',
      reviewToken: 'ember-summer-7k9qA4mT8vR2xP6cN1',
      budgetLabel: '$4,800',
      owner: 'Maya Okeke',
      revisions: [
        {
          id: 'rev-ember-1',
          label: 'Initial direction',
          version: 1,
          fileName: 'ember-summer-v1.png',
          fileUrl: '/assets/ember-v1.svg',
          thumbnail: '/assets/ember-v1.svg',
          kind: 'image',
          uploadedAt: isoDaysAgo(8),
          uploadedBy: 'Maya Okeke',
          sizeLabel: '3.2 MB',
          note: 'First visual direction with the original orange palette.',
        },
        {
          id: 'rev-ember-2',
          label: 'Colour exploration',
          version: 2,
          fileName: 'ember-summer-v2.png',
          fileUrl: '/assets/ember-v2.svg',
          thumbnail: '/assets/ember-v2.svg',
          kind: 'image',
          uploadedAt: isoDaysAgo(4),
          uploadedBy: 'Maya Okeke',
          sizeLabel: '3.4 MB',
          note: 'Introduced mint, cream, and the larger seasonal lockup.',
        },
        {
          id: 'rev-ember-3',
          label: 'Final refinement',
          version: 3,
          fileName: 'ember-summer-v3.png',
          fileUrl: '/assets/ember-v3.svg',
          thumbnail: '/assets/ember-v3.svg',
          kind: 'image',
          uploadedAt: isoDaysAgo(1),
          uploadedBy: 'Maya Okeke',
          sizeLabel: '3.5 MB',
          note: 'Tightened hierarchy, corrected nutrition panel, and balanced the three-pack composition.',
        },
      ],
      comments: [
        {
          id: 'comment-ember-1',
          projectId: 'project-ember-packaging',
          revisionId: 'rev-ember-2',
          author: 'Dara Okafor',
          authorRole: 'client',
          body: 'Could the seasonal badge feel less loud? It competes with the product name here.',
          status: 'resolved',
          createdAt: isoDaysAgo(3),
          resolvedAt: isoDaysAgo(2),
          x: 73,
          y: 24,
          reply: 'Reduced by 18% and moved into the upper grid line in V3.',
        },
        {
          id: 'comment-ember-2',
          projectId: 'project-ember-packaging',
          revisionId: 'rev-ember-2',
          author: 'Dara Okafor',
          authorRole: 'client',
          body: 'The mint is great. Please keep this exact shade for the cold brew bottle.',
          status: 'resolved',
          createdAt: isoDaysAgo(3),
          resolvedAt: isoDaysAgo(2),
          x: 28,
          y: 49,
          reply: 'Locked as the primary seasonal mint token.',
        },
        {
          id: 'comment-ember-3',
          projectId: 'project-ember-packaging',
          revisionId: 'rev-ember-3',
          author: 'Dara Okafor',
          authorRole: 'client',
          body: 'Can we confirm the small origin text still passes print legibility at final size?',
          status: 'open',
          createdAt: isoDaysAgo(0, 2),
          x: 45,
          y: 72,
        },
      ],
      milestones: [
        { id: 'mile-ember-1', title: 'Creative direction', dueAt: isoDaysAgo(12), status: 'complete' },
        { id: 'mile-ember-2', title: 'Packaging concepts', dueAt: isoDaysAgo(5), status: 'complete' },
        { id: 'mile-ember-3', title: 'Final approval', dueAt: isoDaysAhead(4), status: 'current' },
        { id: 'mile-ember-4', title: 'Production handoff', dueAt: isoDaysAhead(8), status: 'upcoming' },
      ],
      decisions: [],
    },
    {
      id: 'project-loom-editorial',
      name: 'Autumn Editorial Campaign',
      clientId: 'client-loom',
      clientName: 'Loom House',
      category: 'Campaign',
      status: 'changes-requested',
      dueAt: isoDaysAhead(7),
      updatedAt: isoDaysAgo(1),
      progress: 61,
      description: 'Campaign concept and launch assets for Loom House’s autumn furniture collection.',
      cover: '/assets/loom.svg',
      reviewToken: 'loom-autumn-4f2mQ8sL1wZ6kB3dY9',
      budgetLabel: '$6,200',
      owner: 'Maya Okeke',
      revisions: [
        {
          id: 'rev-loom-1',
          label: 'Campaign concept',
          version: 1,
          fileName: 'loom-autumn-concept.png',
          fileUrl: '/assets/loom.svg',
          thumbnail: '/assets/loom.svg',
          kind: 'image',
          uploadedAt: isoDaysAgo(3),
          uploadedBy: 'Noah Reed',
          sizeLabel: '5.8 MB',
          note: 'First art direction and homepage hero composition.',
        },
      ],
      comments: [
        {
          id: 'comment-loom-1',
          projectId: 'project-loom-editorial',
          revisionId: 'rev-loom-1',
          author: 'Mina Cole',
          authorRole: 'client',
          body: 'The copy needs to feel warmer and less architectural. The image direction is right.',
          status: 'open',
          createdAt: isoDaysAgo(1),
          x: 58,
          y: 21,
        },
        {
          id: 'comment-loom-2',
          projectId: 'project-loom-editorial',
          revisionId: 'rev-loom-1',
          author: 'Mina Cole',
          authorRole: 'client',
          body: 'Please include one mobile crop before the next review.',
          status: 'open',
          createdAt: isoDaysAgo(1),
          x: 82,
          y: 66,
        },
      ],
      milestones: [
        { id: 'mile-loom-1', title: 'Art direction', dueAt: isoDaysAgo(3), status: 'complete' },
        { id: 'mile-loom-2', title: 'Campaign system', dueAt: isoDaysAhead(2), status: 'current' },
        { id: 'mile-loom-3', title: 'Launch assets', dueAt: isoDaysAhead(7), status: 'upcoming' },
      ],
      decisions: [
        {
          id: 'decision-loom-1',
          type: 'changes-requested',
          revisionId: 'rev-loom-1',
          clientName: 'Mina Cole',
          clientEmail: 'mina@loom.example',
          note: 'Please warm up the copy and include a mobile crop.',
          createdAt: isoDaysAgo(1),
          receiptCode: 'PND-LOOM-1047',
        },
      ],
    },
    {
      id: 'project-field-site',
      name: 'Portfolio Site System',
      clientId: 'client-field',
      clientName: 'Field Notes Studio',
      category: 'Web Design',
      status: 'draft',
      dueAt: isoDaysAhead(13),
      updatedAt: isoDaysAgo(2),
      progress: 34,
      description: 'A restrained portfolio and case-study system for a multidisciplinary architecture studio.',
      cover: '/assets/field.svg',
      reviewToken: 'field-site-8p1dH7nV4cR9tM2xK5',
      budgetLabel: '$7,500',
      owner: 'Maya Okeke',
      revisions: [
        {
          id: 'rev-field-1',
          label: 'Homepage wireframe',
          version: 1,
          fileName: 'field-home-wireframe.png',
          fileUrl: '/assets/field.svg',
          thumbnail: '/assets/field.svg',
          kind: 'image',
          uploadedAt: isoDaysAgo(2),
          uploadedBy: 'Maya Okeke',
          sizeLabel: '2.1 MB',
          note: 'Internal wireframe before client review.',
        },
      ],
      comments: [],
      milestones: [
        { id: 'mile-field-1', title: 'Content model', dueAt: isoDaysAgo(1), status: 'complete' },
        { id: 'mile-field-2', title: 'Design system', dueAt: isoDaysAhead(5), status: 'current' },
        { id: 'mile-field-3', title: 'Prototype review', dueAt: isoDaysAhead(13), status: 'upcoming' },
      ],
      decisions: [],
    },
    {
      id: 'project-ember-menu',
      name: 'Retail Menu Refresh',
      clientId: 'client-ember',
      clientName: 'Ember Coffee',
      category: 'Print',
      status: 'approved',
      dueAt: isoDaysAgo(2),
      updatedAt: isoDaysAgo(2),
      progress: 100,
      description: 'Updated seasonal menu boards and table cards for Ember Coffee retail locations.',
      cover: '/assets/menu.svg',
      reviewToken: 'ember-menu-2c8nJ6pS3zW9bF1qL4',
      budgetLabel: '$1,900',
      owner: 'Maya Okeke',
      revisions: [
        {
          id: 'rev-menu-1',
          label: 'Final menu set',
          version: 2,
          fileName: 'ember-menu-final.pdf',
          fileUrl: '/assets/menu.svg',
          thumbnail: '/assets/menu.svg',
          kind: 'pdf',
          uploadedAt: isoDaysAgo(4),
          uploadedBy: 'Noah Reed',
          sizeLabel: '8.4 MB',
          note: 'Press-ready menu system with crop marks and linked fonts.',
        },
      ],
      comments: [],
      milestones: [
        { id: 'mile-menu-1', title: 'Layout', dueAt: isoDaysAgo(9), status: 'complete' },
        { id: 'mile-menu-2', title: 'Approval', dueAt: isoDaysAgo(3), status: 'complete' },
        { id: 'mile-menu-3', title: 'Print handoff', dueAt: isoDaysAgo(2), status: 'complete' },
      ],
      decisions: [
        {
          id: 'decision-menu-1',
          type: 'approved',
          revisionId: 'rev-menu-1',
          clientName: 'Dara Okafor',
          clientEmail: 'dara@ember.example',
          note: 'Approved for production.',
          createdAt: isoDaysAgo(3),
          receiptCode: 'PND-EMBER-8821',
        },
      ],
    },
  ],
  activities: [
    {
      id: 'activity-1',
      type: 'comment',
      title: 'New comment on Summer Packaging Redesign',
      detail: 'Dara asked about print legibility on the origin text.',
      actor: 'Dara Okafor',
      projectId: 'project-ember-packaging',
      createdAt: isoDaysAgo(0, 2),
    },
    {
      id: 'activity-2',
      type: 'upload',
      title: 'Revision 3 uploaded',
      detail: 'Final refinement was added to Summer Packaging Redesign.',
      actor: 'Maya Okeke',
      projectId: 'project-ember-packaging',
      createdAt: isoDaysAgo(1),
    },
    {
      id: 'activity-3',
      type: 'approval',
      title: 'Changes requested',
      detail: 'Mina requested warmer copy and a mobile crop.',
      actor: 'Mina Cole',
      projectId: 'project-loom-editorial',
      createdAt: isoDaysAgo(1),
    },
    {
      id: 'activity-4',
      type: 'approval',
      title: 'Retail Menu Refresh approved',
      detail: 'The final menu set is cleared for production.',
      actor: 'Dara Okafor',
      projectId: 'project-ember-menu',
      createdAt: isoDaysAgo(3),
    },
    {
      id: 'activity-5',
      type: 'invite',
      title: 'Theo invited to Pind',
      detail: 'A secure review link was created for Field Notes Studio.',
      actor: 'Maya Okeke',
      projectId: 'project-field-site',
      createdAt: isoDaysAgo(3),
    },
  ],
  notifications: [
    {
      id: 'notification-1',
      title: 'New client comment',
      body: 'Dara commented on revision 3 of Summer Packaging Redesign.',
      read: false,
      createdAt: isoDaysAgo(0, 2),
      projectId: 'project-ember-packaging',
    },
    {
      id: 'notification-2',
      title: 'Changes requested',
      body: 'Loom House requested changes on the campaign concept.',
      read: false,
      createdAt: isoDaysAgo(1),
      projectId: 'project-loom-editorial',
    },
    {
      id: 'notification-3',
      title: 'Approval captured',
      body: 'Retail Menu Refresh was approved and a receipt was generated.',
      read: true,
      createdAt: isoDaysAgo(3),
      projectId: 'project-ember-menu',
    },
  ],
};
