import { ArrowLeft, Bell, Check, CheckCircle2, Download, Info, MessageSquare, Palette, Plus, Search, Sparkles, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useState } from 'react';
import { StatusBadge } from '../components/StatusBadge';
import { Avatar } from '../components/Avatar';
import { Modal } from '../components/Modal';

export function DesignSystemPage() {
  const [modalOpen, setModalOpen] = useState(false);
  return <div className="system-page">
    <aside className="system-sidebar"><Link to="/" className="brand-lockup"><span className="brand-mark">P</span><span>Pind</span></Link><div><span>Foundations</span><a href="#colour">Colour</a><a href="#type">Typography</a><a href="#spacing">Spacing</a></div><div><span>Components</span><a href="#buttons">Buttons</a><a href="#statuses">Statuses</a><a href="#forms">Forms</a><a href="#feedback">Feedback</a></div><Link to="/app" className="button button--outline button--compact"><ArrowLeft size={15} /> Back to app</Link></aside>
    <main className="system-main"><header className="system-hero"><div><div className="eyebrow">Pind design system · v1.0</div><h1>Calm tools for<br />high-stakes feedback.</h1><p>A reusable visual language for client work: editorial surfaces, restrained colour, clear hierarchy, and states that explain themselves.</p></div><div className="system-hero__mark"><Palette size={54} /></div></header>
      <section className="system-section" id="colour"><header><span>01</span><div><h2>Colour</h2><p>Warm neutrals do the structural work. Accent colour is reserved for focus and decisions.</p></div></header><div className="colour-grid"><Swatch name="Ink" value="#1F2421" className="ink" /><Swatch name="Paper" value="#F4F1EB" className="paper" /><Swatch name="Canvas" value="#FCFBF8" className="canvas" /><Swatch name="Pine" value="#2F5D50" className="pine" /><Swatch name="Clay" value="#9B5543" className="clay" /><Swatch name="Line" value="#DCD8CF" className="line" /></div></section>
      <section className="system-section" id="type"><header><span>02</span><div><h2>Typography</h2><p>Large editorial headlines pair with practical interface text and tabular detail.</p></div></header><div className="type-specimens"><div className="type-display"><span>Display / 72</span><strong>Feedback should<br />move the work.</strong></div><div className="type-grid"><div><span>Heading / 32</span><strong>Summer Packaging Redesign</strong></div><div><span>Body / 16</span><p>Keep every revision, decision, and conversation attached to the work it belongs to.</p></div><div><span>Label / 12</span><em>CLIENT REVIEW PORTAL</em></div><div><span>Data / 28</span><b>78%</b></div></div></div></section>
      <section className="system-section" id="buttons"><header><span>03</span><div><h2>Actions</h2><p>Primary actions are decisive. Secondary actions remain quiet until needed.</p></div></header><div className="component-demo"><div className="demo-row"><button className="button button--primary"><Plus size={16} /> New project</button><button className="button button--outline"><Download size={16} /> Download</button><button className="button button--ghost">Cancel</button><button className="button button--danger"><X size={16} /> Request changes</button></div><div className="demo-row"><button className="icon-button icon-button--bordered"><Bell size={17} /></button><button className="icon-button icon-button--bordered"><Search size={17} /></button><button className="button button--primary button--compact"><Check size={14} /> Approve</button><button className="button button--outline button--compact">Compact</button></div></div></section>
      <section className="system-section" id="statuses"><header><span>04</span><div><h2>Status language</h2><p>Every state combines text, tone, and shape. Colour is never the only signal.</p></div></header><div className="component-demo"><div className="demo-row"><StatusBadge status="draft" /><StatusBadge status="in-review" /><StatusBadge status="changes-requested" /><StatusBadge status="approved" /></div><div className="status-explainer"><article><span className="status status--draft">Draft</span><p>Internal work not yet shared.</p></article><article><span className="status status--in-review">In review</span><p>The latest revision is with the client.</p></article><article><span className="status status--changes-requested">Changes requested</span><p>A decision exists and another revision is expected.</p></article><article><span className="status status--approved">Approved</span><p>The revision has a timestamped sign-off.</p></article></div></div></section>
      <section className="system-section" id="forms"><header><span>05</span><div><h2>Forms</h2><p>Labels stay visible, error states are explicit, and help text does not compete with input.</p></div></header><div className="forms-demo"><label className="field"><span>Project name</span><input defaultValue="Summer Packaging Redesign" /></label><label className="field"><span>Client</span><select defaultValue="ember"><option value="ember">Ember Coffee</option><option>Loom House</option></select></label><label className="field"><span>Revision note</span><textarea rows={4} defaultValue="Tightened hierarchy and corrected the nutrition panel." /></label><label className="field field--error"><span>Client email</span><input defaultValue="dara@" /><small>Enter a complete email address.</small></label></div></section>
      <section className="system-section" id="feedback"><header><span>06</span><div><h2>Feedback patterns</h2><p>Comments read like conversations, but decisions remain unambiguous records.</p></div></header><div className="feedback-demo"><article className="comment-card"><div className="comment-card__top"><Avatar name="Dara Okafor" size="sm" /><div><strong>Dara Okafor</strong><span>Client · 12 minutes ago</span></div><em>1</em></div><p>Can we confirm the small origin text still passes print legibility?</p><div className="comment-card__foot"><button><Check size={14} /> Mark resolved</button></div></article><article className="summary-card"><span><Sparkles size={15} /></span><div><strong>Revision brief</strong><p>One open point remains: confirm print legibility for the origin text.</p></div></article><article className="decision-confirmation is-approval"><span><CheckCircle2 size={22} /></span><div><strong>Approve this revision</strong><p>The client decision will be tied to the exact file and stored as a receipt.</p></div></article><article className="integration-hint"><span className="integration-hint__dot" /><p><strong>Connected state</strong>Integration badges explain both capability and configuration.</p></article></div></section>
      <section className="system-section"><header><span>07</span><div><h2>Dialogs and notifications</h2><p>Overlays keep the user in context and confirm the result immediately.</p></div></header><div className="component-demo"><div className="demo-row"><button className="button button--primary" onClick={() => setModalOpen(true)}>Open sample dialog</button><div className="toast toast--success toast--static"><CheckCircle2 size={18} /><div><strong>Revision uploaded</strong><span>The client link now points to the latest work.</span></div></div><div className="toast toast--info toast--static"><Info size={18} /><div><strong>Demo mode</strong><span>Add credentials when you are ready.</span></div></div></div></div></section>
      <footer className="system-footer"><span>Pind design system</span><span>Tokens live in <code>src/styles.css</code></span><Link to="/app">Open the product</Link></footer>
    </main>
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="Invite a client" eyebrow="Sample component"><div className="form-stack"><label className="field"><span>Email address</span><input defaultValue="dara@ember.example" /></label><label className="field"><span>Message</span><textarea rows={4} defaultValue="The latest revision is ready for review." /></label><div className="modal__footer"><button className="button button--ghost" onClick={() => setModalOpen(false)}>Cancel</button><button className="button button--primary" onClick={() => setModalOpen(false)}><MessageSquare size={15} /> Send invitation</button></div></div></Modal>
  </div>;
}

function Swatch({ name, value, className }: { name: string; value: string; className: string }) { return <div className={`swatch swatch--${className}`}><span /><strong>{name}</strong><code>{value}</code></div>; }
